# Generated by Django 2.0 on 2018-11-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_auto_20181110_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerdetails',
            name='rating',
            field=models.IntegerField(default='000', null=True),
        ),
    ]
