# Generated by Django 2.0 on 2018-11-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_auto_20181110_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerdetails',
            name='description',
            field=models.CharField(default='default', max_length=10000, null=True),
        ),
    ]
